# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - id: coincap-tui
  - env:
      - CGO_ENABLED=0
  - ldflags:
    - "-X github.com/tomekz/coincap-tui/cmd.version={{.Env.RELEASE_VERSION}}"
    goos:
      - linux
      - windows
      - darwin
nfpms:
  - maintainer: Tomasz Zadrozny
    id: packages
    description: "coincap-tui let's you check crypto prices in your terminal"
    homepage: 'https://github.com/tomekz/{{ .ProjectName }}'
    license: MIT
    formats:
      - deb
      - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/tomekz/ 
# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
