name: release

on:
  push:
    # run only against tags
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true
      - run: go mod tidy
      - run: go test -v ./...
      - uses: rickstaa/action-get-semver@v1
        id: get_semver
      - name: Set env
        run: echo "RELEASE_VERSION=${{ steps.get_semver.outputs.current_version  }}" >> $GITHUB_ENV
      - name: Test
        run: echo $RELEASE_VERSION 
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURYPUSHTOKEN }}
